server:
    port: 8080
spring:
    application:
        name: spring-boot-bean-search-study
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        url: jdbc:mysql://162.14.64.15:3306/bean-search?serverTimezone=UTC
        password: 'Gzh19980424.'
        username: 'root'

# bean searcher 设置
# 设置分页参数从1开始
bean-searcher:
    params:
        pagination:
            default-size: 20  # 默认分页大小，不设置默认为 15
            start: 1  # 默认分页起始位置，设置为1,不设置默认为 1